# Generated by Django 5.2.17 on 2026-09-08 17:19

import customer_care.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('first', '0008_customer_care_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderActionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cancel', 'درخواست لغو سفارش'), ('return', 'درخواست مرجوعی')], max_length=10, verbose_name='نوع درخواست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('received', 'کالا دریافت شد'), ('refund_pending', 'در انتظار بازگشت وجه'), ('refunded', 'وجه بازگشت داده شد'), ('closed', 'بسته شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('reason', models.CharField(choices=[('changed_mind', 'انصراف از خرید'), ('damaged', 'کالای آسیب\u200cدیده'), ('wrong_item', 'کالای اشتباه ارسال شده'), ('defective', 'کالای معیوب'), ('not_as_described', 'مغایرت با توضیحات'), ('other', 'سایر')], default='other', max_length=30, verbose_name='دلیل')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات کاربر')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت مدیریت')),
                ('refund_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ قابل بازگشت')),
                ('stock_restored', models.BooleanField(default=False, verbose_name='موجودی بازگردانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_requests', to='first.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_action_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست لغو/مرجوعی',
                'verbose_name_plural': 'درخواست\u200cهای لغو/مرجوعی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('unit_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ واحد هنگام درخواست')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_request_items', to='first.orderitem', verbose_name='آیتم سفارش')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customer_care.orderactionrequest', verbose_name='درخواست')),
            ],
            options={
                'verbose_name': 'آیتم مرجوعی',
                'verbose_name_plural': 'آیتم\u200cهای مرجوعی',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=customer_care.models.generate_ticket_reference, editable=False, max_length=20, unique=True, verbose_name='کد تیکت')),
                ('subject', models.CharField(max_length=180, verbose_name='موضوع')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('in_progress', 'در حال بررسی'), ('waiting_user', 'منتظر پاسخ کاربر'), ('answered', 'پاسخ داده شده'), ('closed', 'بسته شده')], db_index=True, default='new', max_length=20, verbose_name='وضعیت')),
                ('priority', models.CharField(choices=[('normal', 'عادی'), ('high', 'مهم'), ('urgent', 'فوری')], default='normal', max_length=12, verbose_name='اولویت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='first.order', verbose_name='سفارش مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت پشتیبانی',
                'verbose_name_plural': 'تیکت\u200cهای پشتیبانی',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='پیام')),
                ('is_staff_reply', models.BooleanField(default=False, verbose_name='پاسخ پشتیبانی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='customer_care.supportticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'پیام پشتیبانی',
                'verbose_name_plural': 'پیام\u200cهای پشتیبانی',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='orderactionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'received', 'refund_pending'])), fields=('order', 'kind'), name='unique_open_order_action_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='orderactionitem',
            constraint=models.UniqueConstraint(fields=('request', 'order_item'), name='unique_item_per_order_action'),
        ),
    ]
