# Generated by Django 5.2.14 on 2026-08-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrole',
            name='display_name',
            field=models.CharField(default='نقش', max_length=100, verbose_name='نام نمایشی'),
        ),
    ]
