# Generated by Django 5.2.14 on 2026-08-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_alter_adminrole_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='customizer_rules',
            field=models.TextField(blank=True, default='[]', verbose_name='قوانین ویرایشگر بصری'),
        ),
    ]
