# Generated by Django 5.2.14 on 2026-08-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_sitesettings_customizer_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='customizer_theme',
            field=models.JSONField(blank=True, default=dict, verbose_name='تم ویرایشگر بصری'),
        ),
    ]
