# Generated by Django 5.2.14 on 2026-08-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_add_fields_to_adminuserpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='number_format',
            field=models.CharField(choices=[('persian', 'فارسی (۱۲۳)'), ('english', 'انگلیسی (123)')], default='persian', max_length=10, verbose_name='فرمت اعداد'),
        ),
    ]
