# Generated by Django 5.2.14 on 2026-08-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_sitesettings_number_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='تصویر دسته\u200cبندی'),
        ),
    ]
