# Generated by Django 5.2.17 on 2026-09-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_secure_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpermission',
            name='name',
            field=models.CharField(choices=[('dashboard', 'داشبورد مدیریت'), ('products_view', 'مشاهده محصولات'), ('products_add', 'افزودن محصول'), ('products_edit', 'ویرایش محصول'), ('products_delete', 'حذف محصول'), ('orders_view', 'مشاهده سفارشات'), ('orders_update', 'تغییر وضعیت سفارش'), ('reviews_view', 'مشاهده نظرات'), ('reviews_verify', 'تایید نظرات'), ('reviews_delete', 'حذف نظرات'), ('users_view', 'مشاهده کاربران'), ('users_manage', 'مدیریت کاربران'), ('admins_manage', 'مدیریت ادمین\u200cها'), ('warehouse_view', 'مشاهده انبار'), ('warehouse_edit', 'ویرایش انبار'), ('site_settings', 'تنظیمات ظاهر'), ('reports_view', 'مشاهده گزارشات'), ('support_view', 'مشاهده تیکت\u200cهای پشتیبانی'), ('support_reply', 'پاسخگویی به تیکت\u200cهای پشتیبانی'), ('returns_manage', 'مدیریت لغو و مرجوعی سفارش\u200cها')], max_length=50, unique=True, verbose_name='نام دسترسی'),
        ),
    ]
